[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true

[[redirects]]
  from = "/fr/article/:slug"
  to = "/fr/blog/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/en/article/:slug"
  to = "/en/blog/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/feed.xml"
  to = "/fr/blog/rss.xml"
  status = 301
  force = true

[[redirects]]
  from = "/pricing"
  to = "/fr/plus"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/pricing"
  to = "/en"
  status = 302
  force = true

[[redirects]]
  from = "/:lang/installation"
  to = "/:lang/docs"
  status = 301
  force = true

[[redirects]]
  from = "/fr/gladys-starter-pack"
  to = "/fr/plus"
  status = 301
  force = true

[[redirects]]
  from = "/fr/gladys-community-package"
  to = "/fr/plus"
  status = 301
  force = true

[[redirects]]
  from = "/fr/pricing"
  to = "/fr/plus"
  status = 301
  force = true

[[redirects]]
  from = "/en/gladys-community-package"
  to = "/en/plus"
  status = 301
  force = true

[[redirects]]
  from = "/en/pricing"
  to = "/en/plus"
  status = 301
  force = true

[[redirects]]
  from = "/pricing/success"
  to = "/fr/payment_success"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/pricing/success"
  to = "/en/payment_success"
  status = 302
  force = true

[[redirects]]
  from = "/download/latest"
  to = "https://cdn.elephantcdn.com/gh/gladysassistant/gladys/releases/download/v4.0.4/gladys-4.0.4-rev4.img.zip"
  status = 302
  force = true